### ISSUE TITLE
Project plan 01/11/2023

### ISSUE THREAD

**Issue by royitaqi** [royitaqi/HollowKnight.BossAttacks#12]
~~The mod will have an enable/disable option in mod menu.~~ We don't need this, because the mod doesn't change boss fights by default, and is only activated per-fight by pressing "0".

~~When enabled,~~ outside boss fights, it will display "Enter a boss fight to select attacks".

When in a non-supported boss, it will display "This boss is not supported".

If the boss is supported, it will display "Press "0" to mod the boss fight and select attacks", which will turn on the modules.

Once a boss fight is modded (by pressing "0"), there is no going back unless to quite the fight.

~~At any time, when the mod is disabled (via mod menu), everything will be unloaded and recovered as if the mod never existed.~~

# These bosses are not interesting
**Will not be supported.**

* [x] GG_Flukemarm
* [x] GG_Ghost_Galien
* [x] GG_Ghost_Gorb
* [x] GG_Ghost_Gorb_V
* [x] GG_Ghost_Markoth
* [x] GG_Ghost_Markoth_V
* [x] GG_Ghost_Marmu
* [x] GG_Ghost_Marmu_V
* [x] GG_Ghost_No_Eyes
* [x] GG_Ghost_No_Eyes_V
* [x] GG_Ghost_Xero
* [x] GG_Ghost_Xero_V
* [x] GG_Oblobbles

# These bosses are *simple*
Will be supported by **generic attack selector**.

* [x] GG_Crystal_Guardian
    * [x] GG_Crystal_Guardian_2

* [x] GG_Dung_Defender
    * [x] **level changer** to turn the following modules on/off
        * [x] **transition rewirer** to trim head throw
    * [x] GG_White_Defender
        * [x] Need to remove attack GROUND SLAM
        * [x] **level changer** to turn the following modules on/off
            * [x] **transition rewirer** to trim head throw
            * [x] **event emitter** to trim tail dive
* [x] GG_God_Tamer
    * [x] Need to remove an attack FINISHED
* [x] GG_Lost_Kin
* [x] GG_Mega_Moss_Charger
* [x] GG_Traitor_Lord
    * [x] Need to remove an attack SLAM
    * [ ] SLAM may occur after other attacks. Can be turned on/off by **phase selector**.
    * [ ] **custom module** is needed to turn on SLAM purely (i.e. without other attacks happening).
* [x] GG_Uumuu
    * [x] GG_Uumuu_V

# These bosses have *row checks*
Will be supported by **generic attack selector + variable setter**.

The **variable setter** is by default turned on when "0" is pressed, allowing the boss to practically skip row checks.

* [x] GG_Brooding_Mawlek
    * [x] Need to rename the attacks from TRUE/FALSE to SPIT/JUMP
    * [x] Need **variable setter** for row checks
        * [x] do not repro
            * [x] Sometimes can JUMP when SPIT is selected
            * [x] Sometimes can SPIT when JUMP is selected
    * [x] GG_Brooding_Mawlek_V
        * [x] do not repro
    * [x] **variable setter** for row checks: "JA In A Row=0", "Slam In A Row=0", "Jump Count=0", "Stunned Amount=-9"
    * [x] Need to remove attacks RUN and TEST
    * [x] GG_False_Knight

* [x] GG_Gruz_Mother
    * [x] **variable setter** for row checks
    * [x] GG_Gruz_Mother_V

# These bosses have *attacks selected through variables*
Will be supported by **variable setter** with the expectation that this option **will override generic attack selector**.

* [x] GG_Broken_Vessel
    * [x] SHAKE

Or, slightly differently, need to set a variable to skip certain constraints (e.g. "first attack must be X").

* [x] GG_Grimm_Nightmare
    * [x] **variable setter** for "first attack must be SLASH"
    * [x] Need to remove an attack BALLOON
    * [x] **event emitter** to prevent FIREBATS after evade in SLASH
    * [x] **level changer + event emitter** to enable BALLOON as level 1

# These bosses have *attacks selected through events*

* [x] GG_Hornet_1
    * [x] **phase selector** to route to the "CAN THROW" Choice State, where **generic attack selector** allow select attacks
    * [ ] THROW can go out of screen

* [x] GG_Hornet_2
    * [ ] THROW can go out of screen
    * [ ] BARB can be turned off by **variable setter** or **phase selector**
    * [ ] BARB **may** be turned on by **variable setter** or **phase selector** (subject to object pool)
    * [ ] SPHERE G can be turned on/off by **variable setter** or **phase selector**

# These bosses are simple *multi-phase* bosses

**Event emitter** or **variable setter** will jump the boss right into its last phase, where it has all the attacks. **Attack selector** is then used on the last Choice state to select attacks.

* [x] GG_Grey_Prince_Zote
    * [x] SPIT SUMMON does JUMP when there are already 3 summons. Use **transition rewirer** to route back to Idle Start.

* [x] GG_Hive_Knight
    * [x] Need to remove an attack JUMP
* [x] GG_Hollow_Knight

Instead of phase selector, some bosses need a **variable setter** to go to its last phase.

* [x] GG_Nosk_Hornet

# These bosses have _multiple phases_ which have _different attacks_

* [x] GG_Radiance
    * [x] **auto level changer** to track AbsRad and arena phase
    * [x] **attack selector** in separate levels for different phases

# These bosses have _multiple GOs_
Need more thoughts on how to support multiple GOs.

* [x] GG_Vengefly_V
    * [x] Separate set of modules for each boss instance
    * [ ] In the future: a **multi-GO module**:
        * [ ] take one set of config
        * [ ] duplicate configs and initialize one set of modules for each GO
        * [ ] return a set of over-arching options, which map to the same option in multiple GOs

# These bosses are _complex_
Will be supported by **custom module**.

* [x] GG_Ghost_Hu
    * [x] **level charger** to model exclusive attacks
    * [x] **event emitter** and **transition rewirer** to skip each attacks

* [x] GG_Mage_Knight
    * [x] Separate attacks exclusively: all, SHOOT, SLASH, STOMP
    * [x] **level changer** to switch between all and attacks
    * [x] **label** to display current selection
    * [x] **SCP** to allow disabling attacks on Move Decision
    * [x] **event emitter** and **transition rewirer** to disable attacks
    * [x] GG_Mage_Knight_V
* [x] GG_Nosk
    * [x] **custom module**
        * [x] Has two Choice states: Idle and Idle No Spit
            * [x] Need to merge attack options across two states: Idle, Idle No Spit
        * [x] If CHARGE is turned off, need to turn off SPIT, too
        * [x] SPIT is actually "charge-spit-charge" and only can trigger when boss isn't in the middle.
            * [x] CHARGE need to be selected when SPIT is selected.
        * [x] ROOF SPIT will be exclusive.
            * [x] When turned on:
                * [x] wire ROAR to RS Jump Antic
                * [x] event emitter in Idle to send ROAR
            * [x] When turned off:
                * [x] event emitter in Roof Jump? to send FINISHED. This prevents roof spit to trail any other attack.
* [x] GG_Sly
    * [x] ~~**custom module** to wire the flow to each attack~~
    * [x] **manual level changers** to model exclusive choices: all, COMBO, STOMP, NA
    * [x] **transition rewirers** to block COMBO and STOMP
    * [x] **variable setter** and **transition rewirer** to block and force NA
    * [x] **auto level changer** to detect the entering of phase 2, thus hides all other options
* [x] GG_Soul_Master
    * [x] **generic attack selector** in phase 1
    * [x] ~~**custom module** to jump to phase 2 (irreversible) and do infinite dive~~
    * [x] **level changer** to change into level 2
        * [x] **event emitter** on Shoot? to prevent shooting
        * [x] **GO killer** to kill phase 1 boss instance
        * [x] **auto level changer** to detect death of phase 1 boss instance
        * [x] **event emitter** x2 to wire infinite dive in phase 2
    * [x] GG_Soul_Tyrant
* [x] GG_Vengefly
    * [x] ~~**custom module** to set variables and rewire CANCEL to Idle or Choose Attack~~
    * [x] **generic attack selector** map SUMMON to append description of its total count limitation
    * [x] **variable setter** to clear row checks
    * [x] **transition rewirer** to Check Summon and Check Summon GG's CANCEL to Idle
* [x] GG_Painter
    * [x] GREAT SLASH needs to be exclusive. Not in the same random selection as other attacks.
    * [x] Two **attack selectors** to control Choice and Evade Choice
        * [ ] Merge the two AS into one
    * [x] Understand FSM's flow (roughly, following the 3 normal attacks; GREAT SLASH can be traced similarly)
        * [x] Excalidraw: https://excalidraw.com/#json=KO8Fn-HhgtAr-QLs2VmXf,ZoPM2bfa-AfK8qj6lyNiDg
        * [x] ![image](https://user-images.githubusercontent.com/14790745/212554015-feaa047e-66b5-4822-b3c7-9377eeac455a.png)
* [x] GG_Mantis_Lords
    * [x] **attack selector** in phase 1 and phase 2 (coordinated mode)
    * [x] both **manual** and **auto level changer** plus **GO killer** to advance to phase 2
    * [x] **manual level changer** in phase 2 to toggle uncoordinated mode
    * [x] **action enabler** x2 to force non-sub logic path in each of the boss in uncoordinated mode
    * [x] Excalidraw: https://excalidraw.com/#json=8lH9m-qOM---Kdnne3Xzu,3dadt2syVqfNT7dz-MbNqQ
    * [x] ![image](https://user-images.githubusercontent.com/14790745/212564155-ec6313d4-93dd-4121-a46e-78b333e605cf.png)
    * [ ] Caveat: doesn't handle the case where a boss is killed in Phase 2
        * [ ] Should remove the AS for coordinated attacks and instead set up AS for the remaining boss
    * [x] GG_Mantis_Lords_V
        * [ ] Same caveat as above, but need to support:
            * [ ] Phase 2 (2 bosses remain coordinated)
            * [ ] Phase 2 (1 boss remain)
* [x] GG_Watcher_Knights
    * [x] Multiple Choice states interconnected. Use **exclusive mode** to wire each attack individually.
    * [x] Multiple GOs. **Option combiner** to map options of all 6 watcher knights into one set of options.

# These bosses I haven't figured out yet

* [x] GG_Collector
* [x] GG_Collector_V
* [ ] GG_Nailmasters

# These bosses seems impossible

* [ ] GG_Grimm
    * [ ] Cannot change transition.
    * [ ] Verified it's the same GO and FSM objects.
    * [ ] Boss states are not printing.

---

**Comment by royitaqi** [comment]
test comment

* [ ] GG_Broken_Vessel
* [ ] GG_Brooding_Mawlek
* [ ] GG_Brooding_Mawlek_V
* [ ] GG_Collector
* [ ] GG_Collector_V
* [ ] GG_Crystal_Guardian
* [ ] GG_Crystal_Guardian_2
* [ ] GG_Dung_Defender
* [ ] GG_Failed_Champion
* [ ] GG_False_Knight
* [ ] GG_Flukemarm
* [ ] GG_Ghost_Galien
* [ ] GG_Ghost_Gorb
* [ ] GG_Ghost_Gorb_V
* [ ] GG_Ghost_Hu
* [ ] GG_Ghost_Markoth
* [ ] GG_Ghost_Markoth_V
* [ ] GG_Ghost_Marmu
* [ ] GG_Ghost_Marmu_V
* [ ] GG_Ghost_No_Eyes
* [ ] GG_Ghost_No_Eyes_V
* [ ] GG_Ghost_Xero
* [ ] GG_Ghost_Xero_V
* [ ] GG_God_Tamer
* [ ] GG_Grey_Prince_Zote
* [ ] GG_Grimm
* [ ] GG_Grimm_Nightmare
* [ ] GG_Gruz_Mother
* [ ] GG_Gruz_Mother_V
* [ ] GG_Hive_Knight
* [ ] GG_Hollow_Knight
* [ ] GG_Hornet_1
* [ ] GG_Hornet_2
* [ ] GG_Lost_Kin
* [ ] GG_Mage_Knight
* [ ] GG_Mage_Knight_V
* [ ] GG_Mantis_Lords
* [ ] GG_Mantis_Lords_V
* [ ] GG_Mega_Moss_Charger
* [ ] GG_Nailmasters
* [ ] GG_Nosk
* [ ] GG_Nosk_Hornet
* [ ] GG_Oblobbles
* [ ] GG_Painter
* [ ] GG_Radiance
* [ ] GG_Sly
* [ ] GG_Soul_Master
* [ ] GG_Soul_Tyrant
* [ ] GG_Traitor_Lord
* [ ] GG_Uumuu
* [ ] GG_Uumuu_V
* [ ] GG_Vengefly
* [ ] GG_Vengefly_V
* [ ] GG_Watcher_Knights
* [ ] GG_White_Defender
